spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Apply to all routes
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true